import { CHFCurrency, Comparison, EURCurrency, ExchangeRate, ExchangeRateManager, GBPCurrency, ITLCurrency, JPYCurrency, Money, SEKCurrency, USDCurrency } from '/ql.mjs';
describe('Exchange-rate tests', () => {
    it('Testing direct exchange rates...', () => {
        const EUR = new EURCurrency(), USD = new USDCurrency();
        const eur_usd = new ExchangeRate().init(EUR, USD, 1.2042);
        const m1 = new Money(EUR, 50000.0);
        const m2 = new Money(USD, 100000.0);
        Money.conversionType = Money.ConversionType.NoConversion;
        let calculated = eur_usd.exchange(m1);
        let expected = new Money(USD, m1.value() * eur_usd.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        calculated = eur_usd.exchange(m2);
        expected = new Money(EUR, m2.value() / eur_usd.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
    });
    it('Testing derived exchange rates...', () => {
        const EUR = new EURCurrency(), USD = new USDCurrency(), GBP = new GBPCurrency();
        const eur_usd = new ExchangeRate().init(EUR, USD, 1.2042);
        const eur_gbp = new ExchangeRate().init(EUR, GBP, 0.6612);
        const derived = ExchangeRate.chain(eur_usd, eur_gbp);
        const m1 = new Money(GBP, 50000.0);
        const m2 = new Money(USD, 100000.0);
        Money.conversionType = Money.ConversionType.NoConversion;
        let calculated = derived.exchange(m1);
        let expected = new Money(USD, m1.value() * eur_usd.rate() / eur_gbp.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        calculated = derived.exchange(m2);
        expected = new Money(GBP, m2.value() * eur_gbp.rate() / eur_usd.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
    });
    it('Testing lookup of direct exchange rates...', () => {
        ExchangeRateManager.clear();
        const EUR = new EURCurrency(), USD = new USDCurrency();
        const eur_usd1 = new ExchangeRate().init(EUR, USD, 1.1983);
        const eur_usd2 = new ExchangeRate().init(USD, EUR, 1.0 / 1.2042);
        ExchangeRateManager.add(eur_usd1, new Date('4-August-2004'));
        ExchangeRateManager.add(eur_usd2, new Date('5-August-2004'));
        const m1 = new Money(EUR, 50000.0);
        const m2 = new Money(USD, 100000.0);
        Money.conversionType = Money.ConversionType.NoConversion;
        let eur_usd = ExchangeRateManager.lookup(EUR, USD, new Date('4-August-2004'), ExchangeRate.Type.Direct);
        let calculated = eur_usd.exchange(m1);
        let expected = new Money(USD, m1.value() * eur_usd1.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        eur_usd = ExchangeRateManager.lookup(EUR, USD, new Date('5-August-2004'), ExchangeRate.Type.Direct);
        calculated = eur_usd.exchange(m1);
        expected = new Money(USD, m1.value() / eur_usd2.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        let usd_eur = ExchangeRateManager.lookup(USD, EUR, new Date('4-August-2004'), ExchangeRate.Type.Direct);
        calculated = usd_eur.exchange(m2);
        expected = new Money(EUR, m2.value() / eur_usd1.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        usd_eur = ExchangeRateManager.lookup(USD, EUR, new Date('5-August-2004'), ExchangeRate.Type.Direct);
        calculated = usd_eur.exchange(m2);
        expected = new Money(EUR, m2.value() * eur_usd2.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
    });
    it('Testing lookup of triangulated exchange rates...', () => {
        ExchangeRateManager.clear();
        const EUR = new EURCurrency(), USD = new USDCurrency(), ITL = new ITLCurrency();
        const eur_usd1 = new ExchangeRate().init(EUR, USD, 1.1983);
        const eur_usd2 = new ExchangeRate().init(EUR, USD, 1.2042);
        ExchangeRateManager.add(eur_usd1, new Date('4-August-2004'));
        ExchangeRateManager.add(eur_usd2, new Date('5-August-2004'));
        const m1 = new Money(ITL, 50000000.0);
        const m2 = new Money(USD, 100000.0);
        Money.conversionType = Money.ConversionType.NoConversion;
        let itl_usd = ExchangeRateManager.lookup(ITL, USD, new Date('4-August-2004'));
        let calculated = itl_usd.exchange(m1);
        let expected = new Money(USD, m1.value() * eur_usd1.rate() / 1936.27);
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        itl_usd = ExchangeRateManager.lookup(ITL, USD, new Date('5-August-2004'));
        calculated = itl_usd.exchange(m1);
        expected = new Money(USD, m1.value() * eur_usd2.rate() / 1936.27);
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        let usd_itl = ExchangeRateManager.lookup(USD, ITL, new Date('4-August-2004'));
        calculated = usd_itl.exchange(m2);
        expected = new Money(ITL, m2.value() * 1936.27 / eur_usd1.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        usd_itl = ExchangeRateManager.lookup(USD, ITL, new Date('5-August-2004'));
        calculated = usd_itl.exchange(m2);
        expected = new Money(ITL, m2.value() * 1936.27 / eur_usd2.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
    });
    it('Testing lookup of derived exchange rates...', () => {
        const EUR = new EURCurrency(), USD = new USDCurrency(), GBP = new GBPCurrency(), CHF = new CHFCurrency(), SEK = new SEKCurrency(), JPY = new JPYCurrency();
        ExchangeRateManager.clear();
        const eur_usd1 = new ExchangeRate().init(EUR, USD, 1.1983);
        const eur_usd2 = new ExchangeRate().init(USD, EUR, 1.0 / 1.2042);
        ExchangeRateManager.add(eur_usd1, new Date('4-August-2004'));
        ExchangeRateManager.add(eur_usd2, new Date('5-August-2004'));
        const eur_gbp1 = new ExchangeRate().init(GBP, EUR, 1.0 / 0.6596);
        const eur_gbp2 = new ExchangeRate().init(EUR, GBP, 0.6612);
        ExchangeRateManager.add(eur_gbp1, new Date('4-August-2004'));
        ExchangeRateManager.add(eur_gbp2, new Date('5-August-2004'));
        const usd_chf1 = new ExchangeRate().init(USD, CHF, 1.2847);
        const usd_chf2 = new ExchangeRate().init(CHF, USD, 1.0 / 1.2774);
        ExchangeRateManager.add(usd_chf1, new Date('4-August-2004'));
        ExchangeRateManager.add(usd_chf2, new Date('5-August-2004'));
        const chf_sek1 = new ExchangeRate().init(SEK, CHF, 0.1674);
        const chf_sek2 = new ExchangeRate().init(CHF, SEK, 1.0 / 0.1677);
        ExchangeRateManager.add(chf_sek1, new Date('4-August-2004'));
        ExchangeRateManager.add(chf_sek2, new Date('5-August-2004'));
        const jpy_sek1 = new ExchangeRate().init(SEK, JPY, 14.5450);
        const jpy_sek2 = new ExchangeRate().init(JPY, SEK, 1.0 / 14.6110);
        ExchangeRateManager.add(jpy_sek1, new Date('4-August-2004'));
        ExchangeRateManager.add(jpy_sek2, new Date('5-August-2004'));
        const m1 = new Money(USD, 100000.0);
        const m2 = new Money(EUR, 100000.0);
        const m3 = new Money(GBP, 100000.0);
        const m5 = new Money(SEK, 100000.0);
        const m6 = new Money(JPY, 100000.0);
        Money.conversionType = Money.ConversionType.NoConversion;
        let usd_sek = ExchangeRateManager.lookup(USD, SEK, new Date('4-August-2004'));
        let calculated = usd_sek.exchange(m1);
        let expected = new Money(SEK, m1.value() * usd_chf1.rate() / chf_sek1.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        usd_sek = ExchangeRateManager.lookup(SEK, USD, new Date('5-August-2004'));
        calculated = usd_sek.exchange(m5);
        expected = new Money(USD, m5.value() * usd_chf2.rate() / chf_sek2.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        let eur_sek = ExchangeRateManager.lookup(EUR, SEK, new Date('4-August-2004'));
        calculated = eur_sek.exchange(m2);
        expected = new Money(SEK, m2.value() * eur_usd1.rate() * usd_chf1.rate() / chf_sek1.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        eur_sek = ExchangeRateManager.lookup(SEK, EUR, new Date('5-August-2004'));
        calculated = eur_sek.exchange(m5);
        expected = new Money(EUR, m5.value() * eur_usd2.rate() * usd_chf2.rate() / chf_sek2.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        let eur_jpy = ExchangeRateManager.lookup(EUR, JPY, new Date('4-August-2004'));
        calculated = eur_jpy.exchange(m2);
        expected = new Money(JPY, m2.value() * eur_usd1.rate() * usd_chf1.rate() * jpy_sek1.rate() /
            chf_sek1.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        eur_jpy = ExchangeRateManager.lookup(JPY, EUR, new Date('5-August-2004'));
        calculated = eur_jpy.exchange(m6);
        expected = new Money(EUR, m6.value() * jpy_sek2.rate() * eur_usd2.rate() * usd_chf2.rate() /
            chf_sek2.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        let gbp_jpy = ExchangeRateManager.lookup(GBP, JPY, new Date('4-August-2004'));
        calculated = gbp_jpy.exchange(m3);
        expected = new Money(JPY, m3.value() * eur_gbp1.rate() * eur_usd1.rate() * usd_chf1.rate() *
            jpy_sek1.rate() / chf_sek1.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
        gbp_jpy = ExchangeRateManager.lookup(JPY, GBP, new Date('5-August-2004'));
        calculated = gbp_jpy.exchange(m6);
        expected = new Money(GBP, m6.value() * jpy_sek2.rate() * eur_usd2.rate() * usd_chf2.rate() *
            eur_gbp2.rate() / chf_sek2.rate());
        expect(Comparison.close(calculated.value(), expected.value())).toBeTruthy();
    });
});
//# sourceMappingURL=exchangerate.js.map